These are the basic Numpy Command for a 1D array.

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])
print(lst)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
lst * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [5]:
print(arr+5)

[ 6  7  8  9 10]


In [6]:
print ( arr / 2)

[0.5 1.  1.5 2.  2.5]


In [7]:
print ( arr ** 2)

[ 1  4  9 16 25]


In [8]:
print("sum: ", np.sum(arr))

sum:  15


In [9]:
print("Mean: ", np.mean(arr))

Mean:  3.0


In [10]:
print("Min: ", np.min(arr))

Min:  1


In [11]:
print("Max: ", np.max(arr))

Max:  5


In [12]:
print(arr[0])

1


In [13]:
print(arr[-1])

5


In [14]:
print(arr[1:3])

[2 3]


In [16]:
print(arr.shape)

(5,)


In [24]:
expense = np.array([100, 50, 120, 200, 250, 20])
total_expense = np.sum(expense)
average_expense = np.mean(expense)
highest_expense = np.max(expense)
taxed_expense = expense * 1.1
print(f"Total:{total_expense}, Average: {average_expense}, Highest: {highest_expense}, Taxed: {taxed_expense}")

Total:740, Average: 123.33333333333333, Highest: 250, Taxed: [110.  55. 132. 220. 275.  22.]


Let's Look at 2D arrays now. 

In [35]:
kharcha = np.array([
    [100, 50, 20],   # Day 1: food, transport, misc
    [120, 60, 30],   # Day 2
    [90,  40, 25]    # Day 3
])
print(kharcha)

[[100  50  20]
 [120  60  30]
 [ 90  40  25]]


In [36]:
print(kharcha.shape)

(3, 3)


In [37]:
print(kharcha[0])

[100  50  20]


In [49]:
print(kharcha[1,:])


[120  60  30]


In [52]:
print(np.sum(kharcha, axis=1))

[170 210 155]


In [54]:
scaled = kharcha / np.max(kharcha)
print(scaled)

[[0.83333333 0.41666667 0.16666667]
 [1.         0.5        0.25      ]
 [0.75       0.33333333 0.20833333]]


In [55]:
        #Categories #A    #B   #C
weekly = np.array([[100, 200, 300], #Monday
                   [120, 220, 290], #Tuesday
                   [110,240, 200]]) #Wednesday

In [58]:
total_A = np.sum(weekly[:,0])
print(total_A)

330


In [59]:
total_B = np.sum(weekly[:,1])
print(total_B)

660


In [60]:
total_C = np.sum(weekly[:,2])
print(total_C)

790


In [63]:
average_monday = np.mean(weekly[0,:])
print(average_monday)

200.0


In [64]:
average_Tuesday = np.mean(weekly[1,:])
print(average_Tuesday)

210.0


In [68]:
average_Wednesday = np.mean(weekly[2,:])
print(average_Wednesday)

183.33333333333334


In [67]:
highest_weekly_expense = np.max(weekly)
print(highest_weekly_expense)

300


At this point we have completed learning Numpy for 1D and 2D arrays with basic commands. Now, lets move on to the last topic which is Reshaping and broadcasting. Then, we can mark this as completed and move towards learning Pandas. 

In [69]:
data = np.array([100,200,300,400,500,600])
print(data.shape)

(6,)


In [78]:
reshaped = data.reshape(3,2)
print(reshaped)
print(reshaped.shape)

[[100 200]
 [300 400]
 [500 600]]
(3, 2)


In [85]:
auto = data.reshape(3,-1)
print(auto)

[[100 200]
 [300 400]
 [500 600]]


In [86]:
weekly = np.array([
    [100, 200, 300],
    [120, 220, 290],
    [110, 240, 200]
])

tax = np.array([1.1, 1.05, 1.2])

total_with_tax = weekly * tax
print(total_with_tax)

[[110. 210. 360.]
 [132. 231. 348.]
 [121. 252. 240.]]


In [87]:
discount = np.array([10, 20, 30])
print(weekly - discount)

[[ 90 180 270]
 [110 200 260]
 [100 220 170]]


In [88]:
daily_fee = np.array([[10], [10], [10]])
print(weekly + daily_fee)

[[110 210 310]
 [130 230 300]
 [120 250 210]]


In [92]:
oneD_array = np.array([1,2,3,4,5,6,7,8])
oneD_reshaped = oneD_array.reshape(4,2)